// Generated by https://quicktype.io

export interface FetchMemberListDto {
  results: Result[];
  info: Info;
}

export interface Info {
  seed: string;
  results: number;
  page: number;
  version: string;
}

export interface Result {
  gender: Gender;
  name: Name;
  email: string;
  dob: Dob;
  registered: Dob;
  id: ID;
}

export interface Dob {
  date: string;
  age: number;
}

export enum Gender {
  Female = "female",
  Male = "male",
}

export interface ID {
  name: string;
  value: string;
}

export interface Name {
  title: string;
  first: string;
  last: string;
}
